services:
  my-db:
    image: postgres:latest
    container_name: my-db
    environment:
      POSTGRES_DB: nextwork
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpass123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8081:8080"
    depends_on:
      - my-db

volumes:
  pgdata:
